yarnPath: .yarn/releases/yarn-3.2.3.cjs
packageExtensions:
  "@camberi/firecms@*":
    dependencies:
      "clsx": "*"
  "@mui/x-date-pickers@*":
    dependencies:
      "date-fns": "*"
      "@mui/system": "5.x"
  "@uiw/react-md-editor@*":
    dependencies:
      "rehype-prism-plus": "*"
