import { getSiteSettings } from "@/lib/sanity";

export default async function Head() {
  const siteSettings = await getSiteSettings()

  return (
    <>
      <title>{siteSettings.title}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
